name: thiscloud_ui
description: Private reusable Flutter UI framework for Thiscloud products.
version: 0.1.0
publish_to: none
repository: https://github.com/mdesantis1984/thiscloud-center/tree/main/packages/ui_kit
issue_tracker: https://github.com/mdesantis1984/thiscloud-center/issues

environment:
  sdk: '>=3.13.1 <4.0.0'
  flutter: '>=3.47.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterVariable.ttf
        - asset: assets/fonts/InterVariable-Italic.ttf
          style: italic
